# Generated by Django 5.2.8 on 2025-11-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('contact_person_phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('rc_number', models.CharField(blank=True, help_text='Registration number', max_length=50)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=50)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['name'],
            },
        ),
    ]
