# Generated by Django 5.2.8 on 2025-11-28 21:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0003_employeedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_statutory_earnings', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_additional_earnings', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pension', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('nhf', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_statutory_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_additional_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clients.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payrolls',
                'db_table': 'payrolls',
                'ordering': ['-period__start_date', 'employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='If True, this deduction will be added to future payrolls for this employee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clients.client')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.payroll')),
            ],
            options={
                'verbose_name': 'Payroll Deduction',
                'verbose_name_plural': 'Payroll Deductions',
                'db_table': 'payroll_deductions',
                'ordering': ['payroll', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='If True, this earning will be added to future payrolls for this employee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clients.client')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='payroll.payroll')),
            ],
            options={
                'verbose_name': 'Payroll Earning',
                'verbose_name_plural': 'Payroll Earnings',
                'db_table': 'payroll_earnings',
                'ordering': ['payroll', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-Weekly')], default='MONTHLY', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clients.client')),
            ],
            options={
                'verbose_name': 'Payroll Period',
                'verbose_name_plural': 'Payroll Periods',
                'db_table': 'payroll_periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='payroll.payrollperiod'),
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable_pension', models.BooleanField(default=True)),
                ('pension_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0800'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('enable_nhf', models.BooleanField(default=True, help_text='National Housing Fund')),
                ('nhf_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0250'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('enable_tax', models.BooleanField(default=True)),
                ('tax_free_allowance', models.DecimalField(decimal_places=2, default=Decimal('200000.00'), max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clients.client')),
            ],
            options={
                'verbose_name': 'Payroll Setting',
                'verbose_name_plural': 'Payroll Settings',
                'db_table': 'payroll_settings',
            },
        ),
        migrations.CreateModel(
            name='StatutoryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_percentage', models.BooleanField(default=False, help_text='If True, amount is a percentage of basic salary')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fixed amount or percentage (0.05 = 5%)', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clients.client')),
            ],
            options={
                'verbose_name': 'Statutory Deduction',
                'verbose_name_plural': 'Statutory Deductions',
                'db_table': 'statutory_deductions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_percentage', models.BooleanField(default=False, help_text='If True, amount is a percentage of basic salary')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fixed amount or percentage (0.15 = 15%)', max_digits=12)),
                ('is_taxable', models.BooleanField(default=True, help_text='Include in taxable income')),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clients.client')),
            ],
            options={
                'verbose_name': 'Statutory Earning',
                'verbose_name_plural': 'Statutory Earnings',
                'db_table': 'statutory_earnings',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'period')},
        ),
    ]
