# Generated by Django 5.2.8 on 2025-12-03 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0003_employeedocument'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clients.client')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='payroll.payrollperiod')),
            ],
            options={
                'verbose_name': 'Payroll Batch',
                'verbose_name_plural': 'Payroll Batches',
                'db_table': 'payroll_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payroll',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='payroll.payrollbatch'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'batch')},
        ),
    ]
